apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-tnac
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-tnac@sha256:81024532879698b1ed967b1e6efd984acbc0d9afa8ad8f17e89376644cc4bd41
        name: my-nodejs
        resources: {}
status: {}
