apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-4od7
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/devfile-sample-python-basic-4od7@sha256:401ee0db712bdc649ea67d88e5bea1274a07e68b682dd8a26d1da1ef04be61dd
        name: my-python
        resources: {}
status: {}
